import { ROLES, type Role } from "./roles";

export const PERMISSIONS = {
  AUTH_ME: "auth:me",

  COMPANY_CREATE: "company:create",
  COMPANY_READ: "company:read",
  COMPANY_UPDATE: "company:update",

  ROUTE_CREATE: "route:create",
  ROUTE_READ: "route:read",
  ROUTE_UPDATE: "route:update",
  ROUTE_DELETE: "route:delete",

  VEHICLE_CREATE: "vehicle:create",
  VEHICLE_READ: "vehicle:read",
  VEHICLE_UPDATE: "vehicle:update",
  VEHICLE_DELETE: "vehicle:delete",

  TRIP_CREATE: "trip:create",
  TRIP_READ: "trip:read",
  TRIP_UPDATE: "trip:update",
  TRIP_CANCEL: "trip:cancel",

  PASSENGER_CREATE: "passenger:create",
  PASSENGER_READ: "passenger:read",
  PASSENGER_UPDATE: "passenger:update",

  BOOKING_CREATE_COMPANY: "booking:create_company",
  BOOKING_CREATE_OWN: "booking:create_own",
  BOOKING_READ_COMPANY: "booking:read_company",
  BOOKING_READ_OWN: "booking:read_own",
  BOOKING_CONFIRM: "booking:confirm",
  BOOKING_CANCEL_COMPANY: "booking:cancel_company",
  BOOKING_CANCEL_OWN: "booking:cancel_own",

  NOTIFICATION_READ_COMPANY: "notification:read_company",
  AUDIT_READ: "audit:read"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const allPermissions = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: allPermissions,
  [ROLES.COMPANY_OWNER]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.ROUTE_CREATE,
    PERMISSIONS.ROUTE_READ,
    PERMISSIONS.ROUTE_UPDATE,
    PERMISSIONS.ROUTE_DELETE,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.VEHICLE_DELETE,
    PERMISSIONS.TRIP_CREATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.TRIP_UPDATE,
    PERMISSIONS.TRIP_CANCEL,
    PERMISSIONS.PASSENGER_CREATE,
    PERMISSIONS.PASSENGER_READ,
    PERMISSIONS.PASSENGER_UPDATE,
    PERMISSIONS.BOOKING_CREATE_COMPANY,
    PERMISSIONS.BOOKING_READ_COMPANY,
    PERMISSIONS.BOOKING_CONFIRM,
    PERMISSIONS.BOOKING_CANCEL_COMPANY,
    PERMISSIONS.NOTIFICATION_READ_COMPANY,
    PERMISSIONS.AUDIT_READ
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.ROUTE_CREATE,
    PERMISSIONS.ROUTE_READ,
    PERMISSIONS.ROUTE_UPDATE,
    PERMISSIONS.ROUTE_DELETE,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.VEHICLE_DELETE,
    PERMISSIONS.TRIP_CREATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.TRIP_UPDATE,
    PERMISSIONS.TRIP_CANCEL,
    PERMISSIONS.PASSENGER_CREATE,
    PERMISSIONS.PASSENGER_READ,
    PERMISSIONS.PASSENGER_UPDATE,
    PERMISSIONS.BOOKING_CREATE_COMPANY,
    PERMISSIONS.BOOKING_READ_COMPANY,
    PERMISSIONS.BOOKING_CONFIRM,
    PERMISSIONS.BOOKING_CANCEL_COMPANY,
    PERMISSIONS.NOTIFICATION_READ_COMPANY,
    PERMISSIONS.AUDIT_READ
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.ROUTE_READ,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.PASSENGER_CREATE,
    PERMISSIONS.PASSENGER_READ,
    PERMISSIONS.PASSENGER_UPDATE,
    PERMISSIONS.BOOKING_CREATE_COMPANY,
    PERMISSIONS.BOOKING_READ_COMPANY,
    PERMISSIONS.BOOKING_CONFIRM,
    PERMISSIONS.BOOKING_CANCEL_COMPANY,
    PERMISSIONS.NOTIFICATION_READ_COMPANY
  ],
  [ROLES.DRIVER]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.BOOKING_READ_COMPANY
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.COMPANY_CREATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.BOOKING_CREATE_OWN,
    PERMISSIONS.BOOKING_READ_OWN,
    PERMISSIONS.BOOKING_CANCEL_OWN
  ]
};

export const hasPermission = (role: Role, permission: Permission) =>
  ROLE_PERMISSIONS[role]?.includes(permission) ?? false;

export const hasAnyPermission = (role: Role, permissions: Permission[]) =>
  permissions.some((permission) => hasPermission(role, permission));
